import AsukaImg from "../assets/dakimakures/asuka_dakimakura.png";
import RemImg from "../assets/dakimakures/rem-dakimakura.png";
import HatsukeMiku from "../assets/dakimakures/hatsune-miko.png";
import Prihozhin from "../assets/dakimakures/prihozhin-zhenia.png";
import Zoro from "../assets/dakimakures/zoro.png";
import ReiImg from "../assets/dakimakures/rei-dakimakura.png";
import LeviImg from "../assets/dakimakures/levi_dakimakura.png";
import GojoImg from "../assets/dakimakures/gojo.png";
import SukunaImg from "../assets/dakimakures/sukuna.png";
import NarutoImg from "../assets/dakimakures/naturo.png";
import SasukeImg from "../assets/dakimakures/sasuke.png";
import ZeroTwoImg from "../assets/dakimakures/zero-two.png";
import KanekiImg from "../assets/dakimakures/ken.png";
import TanjiroImg from "../assets/dakimakures/tanjiro.png";
import NezukoImg from "../assets/dakimakures/nezuko.png";
import GokuImg from "../assets/dakimakures/goku.png";
import MakimaImg from "../assets/dakimakures/makima.png";
import MinatoImg from "../assets/dakimakures/minato.png";
import SaitamaImg from "../assets/dakimakures/saitama.png";
import KilluaImg from "../assets/dakimakures/killua.png";
import AyanokojiImg from "../assets/dakimakures/ayanokoji.png";
import ErenImg from "../assets/dakimakures/eren.png";
import PowerImg from "../assets/dakimakures/power.png";

const dakimakuras = [
  {
    id: 1,
    name: "Асука Лэнгли",
    anime: "Neon Genesis Evangelion",
    price: 2490,
    sizes: ["150x50", "160x50"],
    image: AsukaImg,
    isDoubleSided: true,
    rating: 4.9,
    inStock: true,
    material: "Полистер",
    color: "#ca5b4c",
  },
  {
    id: 2,
    name: "Рей Аянами",
    anime: "Neon Genesis Evangelion",
    price: 2390,
    sizes: ["150x50"],
    image: ReiImg,
    isDoubleSided: true,
    rating: 4.8,
    inStock: true,
    material: "Атлас",
    color: "#a4c2e6",
  },
  {
    id: 3,
    name: "Леви Аккерман",
    anime: "Attack on Titan",
    price: 2690,
    sizes: ["150x50", "180x60"],
    image: LeviImg,
    isDoubleSided: true,
    rating: 5.0,
    inStock: true,
    material: "Полиэстер",
    color: "#3b4d3d",
  },
  {
    id: 4,
    name: "Эрен Йегер",
    anime: "Attack on Titan",
    price: 2550,
    sizes: ["160x50", "180x60"],
    image: ErenImg,
    isDoubleSided: false,
    rating: 4.6,
    inStock: true,
    material: "Атлас",
    color: "#5c4033",
  },
  {
    id: 5,
    name: "Сатору Годжо",
    anime: "Jujutsu Kaisen",
    price: 2990,
    sizes: ["150x50", "160x50", "180x60"],
    image: GojoImg,
    isDoubleSided: true,
    rating: 5.0,
    inStock: true,
    material: "Полистер",
    color: "#994eac",
  },
  {
    id: 6,
    name: "Сукуна Рёмен",
    anime: "Jujutsu Kaisen",
    price: 2800,
    sizes: ["180x60"],
    image: SukunaImg,
    isDoubleSided: true,
    rating: 4.7,
    inStock: false,
    material: "Атлас",
    color: "#803333",
  },
  {
    id: 7,
    name: "Наруто Узумаки",
    anime: "Naruto",
    price: 2200,
    sizes: ["150x50", "160x50"],
    image: NarutoImg,
    isDoubleSided: false,
    rating: 4.5,
    inStock: true,
    material: "Полиэстер",
    color: "#ff9900",
  },
  {
    id: 8,
    name: "Саске Учиха",
    anime: "Naruto",
    price: 2450,
    sizes: ["160x50"],
    image: SasukeImg,
    isDoubleSided: true,
    rating: 4.8,
    inStock: true,
    material: "Полистер",
    color: "#2a2d4a",
  },
  {
    id: 9,
    name: "Зеро Цу (02)",
    anime: "Darling in the Franxx",
    price: 2750,
    sizes: ["150x50", "180x60"],
    image: ZeroTwoImg,
    isDoubleSided: true,
    rating: 4.9,
    inStock: true,
    material: "Атлас",
    color: "#ffb3ba",
  },
  {
    id: 10,
    name: "Кен Канеки",
    anime: "Tokyo Ghoul",
    price: 2400,
    sizes: ["150x50", "160x50", "180x60"],
    image: KanekiImg,
    isDoubleSided: true,
    rating: 4.7,
    inStock: true,
    material: "Полиэстер",
    color: "#464545",
  },
  {
    id: 11,
    name: "Рем",
    anime: "Re:Zero",
    price: 2350,
    sizes: ["150x50"],
    image: RemImg,
    isDoubleSided: true,
    rating: 4.9,
    inStock: true,
    material: "Атлас",
    color: "#4a90e2",
  },
  {
    id: 12,
    name: "Танджиро Камадо",
    anime: "Demon Slayer",
    price: 2300,
    sizes: ["160x50"],
    image: TanjiroImg,
    isDoubleSided: false,
    rating: 4.4,
    inStock: true,
    material: "Полистер",
    color: "#2b797c",
  },
  {
    id: 13,
    name: "Незуко Камадо",
    anime: "Demon Slayer",
    price: 2600,
    sizes: ["150x50", "160x50"],
    image: NezukoImg,
    isDoubleSided: true,
    rating: 4.9,
    inStock: true,
    material: "Атлас",
    color: "#e085a5",
  },
  {
    id: 14,
    name: "Сон Гоку",
    anime: "Dragon Ball Z",
    price: 2100,
    sizes: ["180x60"],
    image: GokuImg,
    isDoubleSided: false,
    rating: 4.3,
    inStock: true,
    material: "Полиэстер",
    color: "#00ffdd",
  },
  {
    id: 15,
    name: "Макима",
    anime: "Chainsaw Man",
    price: 2890,
    sizes: ["150x50", "160x50", "180x60"],
    image: MakimaImg,
    isDoubleSided: true,
    rating: 5.0,
    inStock: true,
    material: "Полистер",
    color: "#ca6969",
  },
  {
    id: 16,
    name: "Пауэр",
    anime: "Chainsaw Man",
    price: 2590,
    sizes: ["150x50", "180x60"],
    image: PowerImg,
    isDoubleSided: true,
    rating: 4.8,
    inStock: true,
    material: "Атлас",
    color: "#f3a661",
  },
  {
    id: 17,
    name: "Минато Намикадзе",
    anime: "Naruto",
    price: 2400,
    sizes: ["160x50", "180x60"],
    image: MinatoImg,
    isDoubleSided: true,
    rating: 4.7,
    inStock: false,
    material: "Полиэстер",
    color: "#f6e05e",
  },
  {
    id: 18,
    name: "Сайтама",
    anime: "One Punch Man",
    price: 1990,
    sizes: ["150x50"],
    image: SaitamaImg,
    isDoubleSided: false,
    rating: 4.6,
    inStock: true,
    material: "Полистер",
    color: "#ffcc00",
  },
  {
    id: 19,
    name: "Килуа Золдик",
    anime: "Hunter x Hunter",
    price: 2480,
    sizes: ["150x50", "160x50"],
    image: KilluaImg,
    isDoubleSided: true,
    rating: 4.9,
    inStock: true,
    material: "Атлас",
    color: "#9ae6b4",
  },
  {
    id: 20,
    name: "Шоэ Аянокоджи",
    anime: "Classroom of the Elite",
    price: 2650,
    sizes: ["160x50", "180x60"],
    image: AyanokojiImg,
    isDoubleSided: true,
    rating: 4.8,
    inStock: true,
    material: "Полиэстер",
    color: "#718096",
  },
];

export default dakimakuras;
